version: '3.8'

services:
  api:
    build: .
    ports:
      - "${EXTERNAL_PORT:-3001}:${PORT:-3000}"  
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}  
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev