version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3000"  # Porta externa 3001, interna 3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev